version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      # This allows anyone to connect to the database
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
